project:
  type: website
#  don't need the pre-render script to generate ToCs any more
#  now that there's the "contents: auto" directive 
#  pre-render: ./prerender

website:
  title: "Ben Fried"
  favicon: assets/safari-pinned-tab.svg
  open-graph:
    locale: en-US
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: nyff2022.html
        text: "The 2022 New York Film Festival"
  
#  sidebar:
#    style: "floating"
#    contents: 
#      - auto: "/*.md"
#      - auto: "/*.qmd"
#      - auto: reviews/*.md

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

#metadata-files:
#    - sidebar.yml
